### ISSUE TITLE
I don't know what is happening -Fake B 

### ISSUE THREAD

**Issue by Nimbus2002** [liamheng/Annotation-free-Fundus-Image-Enhancement#2]
Hello,  and first thank you for the code. 
I am using your SCR net.
and this is the real input image and generated image  by eyeq data. 
Is is right? there is no vessels in fake SB_HFC, SBH, SB. What is the enhanced image name??

![image](https://user-images.githubusercontent.com/66589193/223131484-eab0e12f-7641-4058-aae6-a4c19bc17d53.png)

Thank you in advance

**Comment by Huangqqqhhh** [comment]
I am using your ARC net，can we have a talk?

**Comment by HeverLaw** [comment]
It seems there are some errors in the mask. Since the code runs well in our dataset, we are sorry that we can not tell where the problem is.
