### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by Huangqqqhhh** [liamheng/Annotation-free-Fundus-Image-Enhancement#3]
有白内障的图像经过arcnet“修复”之后的图像，有没有发现其偏红

**Comment by HeverLaw** [comment]
The results of the released weight will be a little bit "red" as you described, and this phenomenon results from the target image dataset we used. Therefore, if you want to customize to adapt to your dataset which might not be so "red", please feel free to develop one with the source code. Thank you.
