### ISSUE TITLE
关于SSIM和PSNR的问题

### ISSUE THREAD

**Issue by qihuiyan1023** [liamheng/Annotation-free-Fundus-Image-Enhancement#6]
你好，我现在正在复现您的GFE-Net网络，但是为什么代码里面没有关于评价指标的内容呢？评价指标部分是在哪里完成的呢？

**Comment by HeverLaw** [comment]
Due to the various dataset constructions and the complexity of our dataset, we have not yet published our evaluation code. We recommend the users use the SSIM and PSNR with skimage, e.g., from skimage.measure import compare_psnr, from skimage.measure import compare_ssim. After that, you can evaluate your own dataset.

**Comment by qihuiyan1023** [comment]
Thank you for taking the time to answer my question. Your response has been very helpful to me. I am reading your paper "A General Fund Image Enhancement Network Boosted by Frequency Self supervised Representation Learning". I have some questions about this paper. Is the innovation of GFE-Net architecture based on the transformation of U-Net? In addition, I have reviewed the code of this paper and found some content about GAN. The innovation of GFE Net was not mentioned in the paper. Could you explain in detail the innovative points of this article? Thank you again for taking the time to read my email, and I look forward to hearing back from you.






颜启慧18742119908
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "liamheng/Annotation-free-Fundus-Image-Enhancement"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月12日(星期三) 上午9:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [liamheng/Annotation-free-Fundus-Image-Enhancement] 关于SSIM和PSNR的问题 (Issue #6)





 
Due to the various dataset constructions and the complexity of our dataset, we have not yet published our evaluation code. We recommend the users use the SSIM and PSNR with skimage, e.g., from skimage.measure import compare_psnr, from skimage.measure import compare_ssim. After that, you can evaluate your own dataset.
